#win
FROM mcr.microsoft.com/windows/nanoserver:1809-amd64
LABEL maintainer https://github.com/WaToI/ \
      version="1.0"
      
WORKDIR app

COPY "./bin/CodeBlockDiagram.exe" CodeBlockDiagram.exe
COPY "./bin/CodeBlockDiagram.pdb" CodeBlockDiagram.pdb
